const std = @import("std");

/// https://curl.se/libcurl/c/libcurl-errors.html
pub const CURLError = error{
    FailedInitialization,
    MalformedURL,
    FeatureNotBuiltIn,
    CouldntResolveHost,
    CouldntResolveProxy,
    CouldntConnect,
    WeirdServerReply,
    RemoteAccessDenied,
    FTPAcceptFailed,
    FTPWeirdPassReply,
    FTPAcceptTimeout,
    FTPWeirdPASVReply,
    FTPWeird222Format,
    FTPCantGetHost,
    HTTP2,
    FTPCouldntSetType,
    FTPCouldntRetrFile,
    PartialFile,
    QuoteError,
    WriteError,
    UploadFailed,
    ReadError,
    OutOfMemory,
    OperationTimeout,
    FTPPortFailed,
    FTPCouldntUseRest,
    RangeError,
    HTTPPostError,
    SSLConnectError,
    BadDownloadResume,
    FileCouldntReadFile,
    LDAPCannotBind,
    LDAPSearchFailed,
    ZLibFunctionNotFound,
    AbortedByCallback,
    BadFunctionArgument,
    InterfaceFailed,
    TooManyRedirects,
    UnknownOption,
    TelnetOptionSyntax,
    GotNothing,
    SSLEngineNotFound,
    SSLEngineSetFailed,
    SendError,
    RecvError,
    SSLCertProblem,
    SSLCipher,
    PeerFailedVerification,
    BadContentEncoding,
    LDAPInvalidURL,
    FilesizeExceeded,
    UseSSLFailed,
    SendFailRewind,
    SSLEngineInitFailed,
    LoginDenied,
    TFPTNotFound,
    TFPTPerm,
    RemoteDiskFull,
    TFTPIllegal,
    TFTPUnknownId,
    RemoteFileExists,
    TFTPNoSuchUser,
    ConvFailed,
    ConvReqd,
    SSLCACERTBadFile,
    RemoteFileNotFound,
    SSH,
    SSLShutdownFailed,
    Again,
    SSLCRLBadFile,
    SSLIssuerError,
    FTPPretFailed,
    RTSPCSEQ,
    RTSPSession,
    FTPBadFileList,
    ChunkFailed,
    NoConnectionAvailable,
    SSLPinnedPubkeyNotMatch,
    SSLInvalidCertStatus,
    HTTPStream,
    RecursiveAPICall,
    AuthError,
    HTTP3,
    QUICConnectError,
    UnknownCURLError,
};

pub fn convertCurlError(code: anytype) !void {
    if (code != .CURLE_OK)
        std.log.debug("convertCurlError( {} )", .{code});
    switch (code) {
        .CURLE_OK => return,
        .CURLE_UNSUPPORTED_PROTOCOL => return error.CouldntResolveHost,
        .CURLE_FAILED_INIT => return error.FailedInitialization,
        .CURLE_URL_MALFORMAT => return error.MalformedURL,
        .CURLE_NOT_BUILT_IN => return error.FeatureNotBuiltIn,
        .CURLE_COULDNT_RESOLVE_PROXY => return error.CouldntResolveProxy,
        .CURLE_COULDNT_RESOLVE_HOST => return error.CouldntResolveHost,
        .CURLE_COULDNT_CONNECT => return error.CouldntConnect,
        .CURLE_WEIRD_SERVER_REPLY => return error.WeirdServerReply,
        .CURLE_REMOTE_ACCESS_DENIED => return error.RemoteAccessDenied,
        .CURLE_FTP_ACCEPT_FAILED => return error.FTPAcceptFailed,
        .CURLE_FTP_WEIRD_PASS_REPLY => return error.FTPWeirdPassReply,
        .CURLE_FTP_ACCEPT_TIMEOUT => return error.FTPAcceptTimeout,
        .CURLE_FTP_WEIRD_PASV_REPLY => return error.FTPWeirdPASVReply,
        .CURLE_FTP_WEIRD_227_FORMAT => return error.FTPWeird222Format,
        .CURLE_FTP_CANT_GET_HOST => return error.FTPCantGetHost,
        .CURLE_HTTP2 => return error.HTTP2,
        .CURLE_FTP_COULDNT_SET_TYPE => return error.FTPCouldntSetType,
        .CURLE_FTP_COULDNT_RETR_FILE => return error.FTPCouldntRetrFile,
        .CURLE_PARTIAL_FILE => return error.PartialFile,
        .CURLE_QUOTE_ERROR => return error.QuoteError,
        .CURLE_WRITE_ERROR => return error.WriteError,
        .CURLE_UPLOAD_FAILED => return error.UploadFailed,
        .CURLE_READ_ERROR => return error.ReadError,
        .CURLE_OUT_OF_MEMORY => return error.OutOfMemory,
        .CURLE_OPERATION_TIMEDOUT => return error.OperationTimeout,
        .CURLE_FTP_PORT_FAILED => return error.FTPPortFailed,
        .CURLE_FTP_COULDNT_USE_REST => return error.FTPCouldntUseRest,
        .CURLE_RANGE_ERROR => return error.RangeError,
        .CURLE_HTTP_POST_ERROR => return error.HTTPPostError,
        .CURLE_SSL_CONNECT_ERROR => return error.SSLConnectError,
        .CURLE_BAD_DOWNLOAD_RESUME => return error.BadDownloadResume,
        .CURLE_FILE_COULDNT_READ_FILE => return error.FileCouldntReadFile,
        .CURLE_LDAP_CANNOT_BIND => return error.LDAPCannotBind,
        .CURLE_LDAP_SEARCH_FAILED => return error.LDAPSearchFailed,
        .CURLE_FUNCTION_NOT_FOUND => return error.ZLibFunctionNotFound,
        .CURLE_ABORTED_BY_CALLBACK => return error.AbortedByCallback,
        .CURLE_BAD_FUNCTION_ARGUMENT => return error.BadFunctionArgument,
        .CURLE_INTERFACE_FAILED => return error.InterfaceFailed,
        .CURLE_TOO_MANY_REDIRECTS => return error.TooManyRedirects,
        .CURLE_UNKNOWN_OPTION => return error.UnknownOption,
        .CURLE_TELNET_OPTION_SYNTAX => return error.TelnetOptionSyntax,
        .CURLE_GOT_NOTHING => return error.GotNothing,
        .CURLE_SSL_ENGINE_NOTFOUND => return error.SSLEngineNotFound,
        .CURLE_SSL_ENGINE_SETFAILED => return error.SSLEngineSetFailed,
        .CURLE_SEND_ERROR => return error.SendError,
        .CURLE_RECV_ERROR => return error.RecvError,
        .CURLE_SSL_CERTPROBLEM => return error.SSLCertProblem,
        .CURLE_SSL_CIPHER => return error.SSLCipher,
        .CURLE_PEER_FAILED_VERIFICATION => return error.PeerFailedVerification,
        .CURLE_BAD_CONTENT_ENCODING => return error.BadContentEncoding,
        .CURLE_LDAP_INVALID_URL => return error.LDAPInvalidURL,
        .CURLE_FILESIZE_EXCEEDED => return error.FilesizeExceeded,
        .CURLE_USE_SSL_FAILED => return error.UseSSLFailed,
        .CURLE_SEND_FAIL_REWIND => return error.SendFailRewind,
        .CURLE_SSL_ENGINE_INITFAILED => return error.SSLEngineInitFailed,
        .CURLE_LOGIN_DENIED => return error.LoginDenied,
        .CURLE_TFTP_NOTFOUND => return error.TFPTNotFound,
        .CURLE_TFTP_PERM => return error.TFPTPerm,
        .CURLE_REMOTE_DISK_FULL => return error.RemoteDiskFull,
        .CURLE_TFTP_ILLEGAL => return error.TFTPIllegal,
        .CURLE_TFTP_UNKNOWNID => return error.TFTPUnknownId,
        .CURLE_REMOTE_FILE_EXISTS => return error.RemoteFileExists,
        .CURLE_TFTP_NOSUCHUSER => return error.TFTPNoSuchUser,
        .CURLE_CONV_FAILED => return error.ConvFailed,
        .CURLE_CONV_REQD => return error.ConvReqd,
        .CURLE_SSL_CACERT_BADFILE => return error.SSLCACERTBadFile,
        .CURLE_REMOTE_FILE_NOT_FOUND => return error.RemoteFileNotFound,
        .CURLE_SSH => return error.SSH,
        .CURLE_SSL_SHUTDOWN_FAILED => return error.SSLShutdownFailed,
        .CURLE_AGAIN => return error.Again,
        .CURLE_SSL_CRL_BADFILE => return error.SSLCRLBadFile,
        .CURLE_SSL_ISSUER_ERROR => return error.SSLIssuerError,
        .CURLE_FTP_PRET_FAILED => return error.FTPPretFailed,
        .CURLE_RTSP_CSEQ_ERROR => return error.RTSPCSEQ,
        .CURLE_RTSP_SESSION_ERROR => return error.RTSPSession,
        .CURLE_FTP_BAD_FILE_LIST => return error.FTPBadFileList,
        .CURLE_CHUNK_FAILED => return error.ChunkFailed,
        .CURLE_NO_CONNECTION_AVAILABLE => return error.NoConnectionAvailable,
        .CURLE_SSL_PINNEDPUBKEYNOTMATCH => return error.SSLPinnedPubkeyNotMatch,
        .CURLE_SSL_INVALIDCERTSTATUS => return error.SSLInvalidCertStatus,
        .CURLE_HTTP2_STREAM => return error.HTTPStream,
        .CURLE_RECURSIVE_API_CALL => return error.RecursiveAPICall,
        .CURLE_AUTH_ERROR => return error.AuthError,
        .CURLE_HTTP3 => return error.HTTP3,
        .CURLE_QUIC_CONNECT_ERROR => return error.QUICConnectError,
        else => return error.UnknownCURLError,
    }
}
